// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_EVzXYOERDZUevtnaP90Q9kJ8Vsa5014',
    appId: '1:919703926369:web:d7c41d5b557fef625e5c20',
    messagingSenderId: '919703926369',
    projectId: 'bouselwawa-6f793',
    authDomain: 'bouselwawa-6f793.firebaseapp.com',
    storageBucket: 'bouselwawa-6f793.firebasestorage.app',
    measurementId: 'G-J6Q5R1MTWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYdEPr790pGu6GVGDpD_iu5_86AFpk3Xs',
    appId: '1:919703926369:android:3e3d3244cf6c663c5e5c20',
    messagingSenderId: '919703926369',
    projectId: 'bouselwawa-6f793',
    storageBucket: 'bouselwawa-6f793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhVDK4YfOgf33gjGqxOkO0IB0GdeGmKvM',
    appId: '1:919703926369:ios:e21c1c1891b9a7ec5e5c20',
    messagingSenderId: '919703926369',
    projectId: 'bouselwawa-6f793',
    storageBucket: 'bouselwawa-6f793.firebasestorage.app',
    iosBundleId: 'com.example.bouselwawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhVDK4YfOgf33gjGqxOkO0IB0GdeGmKvM',
    appId: '1:919703926369:ios:e21c1c1891b9a7ec5e5c20',
    messagingSenderId: '919703926369',
    projectId: 'bouselwawa-6f793',
    storageBucket: 'bouselwawa-6f793.firebasestorage.app',
    iosBundleId: 'com.example.bouselwawa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_EVzXYOERDZUevtnaP90Q9kJ8Vsa5014',
    appId: '1:919703926369:web:337fa40c6e3018fa5e5c20',
    messagingSenderId: '919703926369',
    projectId: 'bouselwawa-6f793',
    authDomain: 'bouselwawa-6f793.firebaseapp.com',
    storageBucket: 'bouselwawa-6f793.firebasestorage.app',
    measurementId: 'G-W53KZK43EC',
  );

}